version = 1

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "8"

[[transformers]]
name = "isort"
enabled = true

[[transformers]]
name = "standardjs"
enabled = true
